"""added to tree

Revision ID: c9bc94fd968a
Revises: 
Create Date: 2025-05-31 11:40:57.841741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bc94fd968a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('road',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('budget', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('map_coordinates', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('road_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_roads', sa.Integer(), nullable=True),
    sa.Column('completed_roads', sa.Integer(), nullable=True),
    sa.Column('in_progress_roads', sa.Integer(), nullable=True),
    sa.Column('planned_roads', sa.Integer(), nullable=True),
    sa.Column('budget_allocated', sa.BigInteger(), nullable=True),
    sa.Column('budget_spent', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['road.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('road_contractor',
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['road.id'], ),
    sa.PrimaryKeyConstraint('road_id', 'contractor_id')
    )
    op.create_table('road_milestone',
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['road.id'], ),
    sa.PrimaryKeyConstraint('road_id', 'milestone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_milestone')
    op.drop_table('road_contractor')
    op.drop_table('photo')
    op.drop_table('notification')
    op.drop_table('user')
    op.drop_table('road_stats')
    op.drop_table('road')
    op.drop_table('milestone')
    op.drop_table('contractor')
    # ### end Alembic commands ###
