"""added one migration

Revision ID: e7714da26b24
Revises: c9bc94fd968a
Create Date: 2025-06-01 07:47:40.143860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7714da26b24'
down_revision = 'c9bc94fd968a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('road', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contractor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('road', schema=None) as batch_op:
        batch_op.drop_column('contractor')

    # ### end Alembic commands ###
