"""done

Revision ID: a4d5f527f8e8
Revises: e7714da26b24
Create Date: 2025-06-03 15:22:48.242559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d5f527f8e8'
down_revision = 'e7714da26b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessibility_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('high_contrast', sa.Boolean(), nullable=True),
    sa.Column('text_size', sa.String(length=10), nullable=True),
    sa.Column('voice_navigation', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accessibility_setting')
    # ### end Alembic commands ###
